const APP_NAME = "Purplecoins";
const DATABASE_NAME = "purplecoins.db";
const BACKUP_EXTENSION = ".purplecoins";
const BACKUP_MIME_TYPE = "application/x-sqlite3";
const ATTACHMENT_MAX_BYTES = 2 * 1024 * 1024;
const DEFAULT_CURRENCY_CODE = "INR";
const DEFAULT_PAGE_SIZE = 100;
const SCHEMA_VERSION = 1;
const EXCHANGE_RATE_API_URL = "https://api.frankfurter.dev/v2/rates";
const MILLISECONDS_PER_DAY = 86_400_000;
const HOMEPAGE_SWITCH_FLAGS: Readonly<{
	ALLOW_SWIPE_SWITCH: boolean;
	ALLOW_CLICK_SWITCH: boolean;
}> = {
	ALLOW_SWIPE_SWITCH: true,
	ALLOW_CLICK_SWITCH: false,
};
const { ALLOW_CLICK_SWITCH, ALLOW_SWIPE_SWITCH } = HOMEPAGE_SWITCH_FLAGS;

export {
	ALLOW_CLICK_SWITCH,
	ALLOW_SWIPE_SWITCH,
	APP_NAME,
	ATTACHMENT_MAX_BYTES,
	BACKUP_EXTENSION,
	BACKUP_MIME_TYPE,
	DATABASE_NAME,
	DEFAULT_CURRENCY_CODE,
	DEFAULT_PAGE_SIZE,
	EXCHANGE_RATE_API_URL,
	MILLISECONDS_PER_DAY,
	SCHEMA_VERSION,
};
