const TRANSACTION_CLASSIFICATIONS = ["GENERAL", "INVESTMENT"] as const;
const TRANSACTION_TYPES = ["DEBIT", "CREDIT", "TRANSFER"] as const;
const BUDGET_PERIODS = ["MONTHLY", "YEARLY"] as const;
const ANALYSIS_PERIODS = [
	"MONTH",
	"YEAR",
	"ALL",
	"CUSTOM",
	"FY",
	"YTD",
] as const;
const RELATION_KINDS = ["SOURCE", "CATEGORY", "TRIP", "INVESTMENT"] as const;
const VAULT_KINDS = ["PASSWORD", "CARD", "IDENTITY"] as const;
const ATTACHMENT_OWNER_TYPES = [
	"TRANSACTION",
	"NOTE",
	"TODO",
	"CARD",
	"IDENTITY",
] as const;
const RATE_SOURCES = ["API", "MANUAL"] as const;

export {
	ANALYSIS_PERIODS,
	ATTACHMENT_OWNER_TYPES,
	BUDGET_PERIODS,
	RATE_SOURCES,
	RELATION_KINDS,
	TRANSACTION_CLASSIFICATIONS,
	TRANSACTION_TYPES,
	VAULT_KINDS,
};
