const {
	withAndroidManifest,
	withDangerousMod,
} = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

const PACKAGE_PATH = "com/purple/coins";
const NATIVE_FILES_DIR = path.join(
	__dirname,
	"native-files",
	"java",
	PACKAGE_PATH,
);

// Files that are copied in verbatim (not merged/generated by Expo),
// overwriting Expo's generated MainActivity.kt / MainApplication.kt and
// adding the UPI notification detector's native module + service.
const FILES_TO_COPY = [
	"MainActivity.kt",
	"MainApplication.kt",
	"UpiNotificationDetectorModule.kt",
	"UpiNotificationDetectorPackage.kt",
	"UpiNotificationListenerService.kt",
];

const withUpiNotificationDetectorManifest = (config) =>
	withAndroidManifest(config, (config) => {
		const manifest = config.modResults;
		const application = manifest.manifest.application[0];

		manifest.manifest["uses-permission"] =
			manifest.manifest["uses-permission"] || [];
		const hasOverlayPermission = manifest.manifest["uses-permission"].some(
			(entry) =>
				entry.$["android:name"] ===
				"android.permission.SYSTEM_ALERT_WINDOW",
		);
		if (!hasOverlayPermission) {
			manifest.manifest["uses-permission"].push({
				$: { "android:name": "android.permission.SYSTEM_ALERT_WINDOW" },
			});
		}

		application.service = application.service || [];
		const hasListenerService = application.service.some(
			(entry) =>
				entry.$["android:name"] === ".UpiNotificationListenerService",
		);
		if (!hasListenerService) {
			application.service.push({
				$: {
					"android:name": ".UpiNotificationListenerService",
					"android:exported": "true",
					"android:permission":
						"android.permission.BIND_NOTIFICATION_LISTENER_SERVICE",
				},
				"intent-filter": [
					{
						action: [
							{
								$: {
									"android:name":
										"android.service.notification.NotificationListenerService",
								},
							},
						],
					},
				],
			});
		}

		return config;
	});

const withUpiNotificationDetectorFiles = (config) =>
	withDangerousMod(config, [
		"android",
		async (config) => {
			const javaRoot = path.join(
				config.modRequest.platformProjectRoot,
				"app",
				"src",
				"main",
				"java",
			);
			const targetDir = path.join(javaRoot, PACKAGE_PATH);
			fs.mkdirSync(targetDir, { recursive: true });

			// Expo also generates its own MainActivity.kt/MainApplication.kt under the
			// full package path (e.g. com/purple/coins/experimental) derived from
			// android.package. Our custom files live one level up (com/purple/coins)
			// but declare that same package, so the generated duplicates must be
			// removed to avoid duplicate class definitions.
			const generatedPackageDir = path.join(
				javaRoot,
				...config.android.package.split("."),
			);
			if (
				generatedPackageDir !== targetDir &&
				fs.existsSync(generatedPackageDir)
			) {
				fs.rmSync(generatedPackageDir, {
					recursive: true,
					force: true,
				});
			}

			for (const fileName of FILES_TO_COPY) {
				fs.copyFileSync(
					path.join(NATIVE_FILES_DIR, fileName),
					path.join(targetDir, fileName),
				);
			}

			return config;
		},
	]);

/**
 * Registers the UPI notification detector native module. Overwrites Expo's
 * generated MainActivity.kt / MainApplication.kt with our custom versions
 * (which already include the standard Expo boilerplate plus our additions),
 * copies the detector module/package/service files, and patches
 * AndroidManifest.xml with the required permission + listener service.
 */
const withUpiNotificationDetector = (config) => {
	config = withUpiNotificationDetectorManifest(config);
	config = withUpiNotificationDetectorFiles(config);
	return config;
};

module.exports = withUpiNotificationDetector;
