enum TransactionRelationType {
	SOURCE = "TRANSACTION_SOURCE",
	TRIP = "TRANSACTION_TRIP",
	CATEGORY = "TRANSACTION_CATEGORY",
	INVESTMENT = "TRANSACTION_INVESTMENT",
	DESTINATION = "TRANSACTION_DESTINATION",
}

export default TransactionRelationType;
